In [26]:
A = "Hi there Sam!"
A.split()

['Hi', 'there', 'Sam!']

In [2]:
planet = "Earth"
diameter = 12742
print(f"The diameter of {planet} is {diameter} Kilometers")

The diameter of Earth is 12742 Kilometers


In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [4]:
import numpy as np


In [16]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [28]:
evenarr=np.arange(20,35,2)
print(evenarr)

[20 22 24 26 28 30 32 34]


In [18]:
matrix=np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
x=np.array([1,2,3])
y=np.array([4,5,6])
concatMatrix=np.concatenate((x,y),axis=None)
print(concatMatrix)

[1 2 3 4 5 6]


In [20]:
import pandas as pd

In [21]:
df=pd.DataFrame(np.arange(0,6).reshape(3,2))
df

0  1
0  0  1
1  2  3
2  4  5

In [22]:
dt=pd.date_range(start='1/1/2023', end='2/10/2023')
pd.Series(dt)

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-11
11   2023-01-12
12   2023-01-13
13   2023-01-14
14   2023-01-15
15   2023-01-16
16   2023-01-17
17   2023-01-18
18   2023-01-19
19   2023-01-20
20   2023-01-21
21   2023-01-22
22   2023-01-23
23   2023-01-24
24   2023-01-25
25   2023-01-26
26   2023-01-27
27   2023-01-28
28   2023-01-29
29   2023-01-30
30   2023-01-31
31   2023-02-01
32   2023-02-02
33   2023-02-03
34   2023-02-04
35   2023-02-05
36   2023-02-06
37   2023-02-07
38   2023-02-08
39   2023-02-09
40   2023-02-10
dtype: datetime64[ns]

In [23]:
list = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(list)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24